import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}


function NavBar() {
  const navItems = [
    {
      name: "About",
      link: "/",
      // icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    {
      name: "Forum",
      link: "/",
      // icon: <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />

    },
    {
      name: "Offers",
      link: "/",
      // icon: <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />

    },
  ];
  return (
    <div className="relative  w-full">
      <FloatingNav navItems={navItems} />
    </div>
  );
}
